In [7]:
import numpy as np
import sympy as sp

Introdução a Cadeias de Markov - exemplo autolocadora

In [86]:
A = np.array([[0.2, 0.2, 0.2, 0.2, 0.2],
              [0.1, 0.4, 0.2, 0.1, 0.2],
              [0.1, 0.3, 0.3, 0.2, 0.1],
              [0.2, 0.2, 0.1, 0.3, 0.2],
              [0.2, 0.3, 0.2, 0.1, 0.2]])

# Linha verificada
x0 = 3 -1

# Numero de iteracoes
xn = 4

M = [A[x0]]
for inter in range(xn-1):
    lin = []
    for k in range(len(A)):
        p = 0
        for i in range(len(A[x0])):
            p += M[inter][i]*A[i][k]
        lin.append(p)
    M.append(lin)

for p in range(len(M)):
    print(p+1, end=' - ')
    for q in range(len(M[0])):
        print(f'{M[p][q]:.4f}', end = '    ')
    print()

1 - 0.1000    0.3000    0.3000    0.2000    0.1000    
2 - 0.1400    0.3000    0.2100    0.1800    0.1700    
3 - 0.1490    0.2980    0.2030    0.1710    0.1790    
4 - 0.1499    0.2978    0.2032    0.1694    0.1797    


Cálculo do limite $\pi_j$

In [87]:
M_pi = np.transpose(A) - np.identity(len(A))
print(M_pi)
M_pi[-1] = np.ones(len(M_pi[0]))
b = np.append(np.zeros(len(M_pi[0])-1), 1)

print()
x = np.linalg.solve(M_pi, b)
for j in range(len(x)):
    print(f'pi_{j+1} = {x[j]:.5f}')

[[-0.8  0.1  0.1  0.2  0.2]
 [ 0.2 -0.6  0.3  0.2  0.3]
 [ 0.2  0.2 -0.7  0.1  0.2]
 [ 0.2  0.1  0.2 -0.7  0.1]
 [ 0.2  0.2  0.1  0.2 -0.8]]

pi_1 = 0.14987
pi_2 = 0.29789
pi_3 = 0.20343
pi_4 = 0.16916
pi_5 = 0.17966


Exemplo 2 urnas com bolas

In [63]:
N = 5
d = []
M = np.zeros((N+1,N+1))

for i in range(N):
    d.append((N-i)/N)

for p in range(N+1):
    for q in range(N+1):
        if abs(p-q) == 1:
            if p<q:
                M[p][q] = d[p]
            else:
                M[p][q] = d[-1-q]

In [64]:
M

array([[0. , 1. , 0. , 0. , 0. , 0. ],
       [0.2, 0. , 0.8, 0. , 0. , 0. ],
       [0. , 0.4, 0. , 0.6, 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.4, 0. ],
       [0. , 0. , 0. , 0.8, 0. , 0.2],
       [0. , 0. , 0. , 0. , 1. , 0. ]])